Refactoring hydro target constraint
NREL-SIIP/PowerSimulations.jl pull request #600
Opened 2021-01-28 16:51 UTC by sourabhdalvi

2021-01-29 07:20 UTC, jd-lara requested changes
I am not sure why we have different functions for energy target hydro and storage. I see a lot of improvement to simplify code here and make functions more generic between the models. 

In principle the common mathematics of both is the same.

2021-01-29 19:14 UTC, sourabhdalvi commented
> I am not sure why we have different functions for energy target hydro and storage. I see a lot of improvement to simplify code here and make functions more generic between the models.
> 
> In principle the common mathematics of both is the same.

2021-01-29 19:16 UTC, jd-lara commented
> > I am not sure why we have different functions for energy target hydro and storage. I see a lot of improvement to simplify code here and make functions more generic between the models.
> > In principle the common mathematics of both is the same.
> 
> I think the make difference between the two is for Storage we are using a static target vs in Hydro the target is a time series. I think we need to add support for both methods for both devices going forward, let talk about this .
> 
> Sorry closed the PR by mistake

The input data shouldn't matter here. I think that there is space to match both, the same model could be used for batteries, hydrogen, hydro. Anything with a book keeping of energy + a storage target should can be modeled this way.

2021-01-29 19:29 UTC, sourabhdalvi commented
> > > I am not sure why we have different functions for energy target hydro and storage. I see a lot of improvement to simplify code here and make functions more generic between the models.
> > > In principle the common mathematics of both is the same.
> > 
> > 
> > I think the make difference between the two is for Storage we are using a static target vs in Hydro the target is a time series. I think we need to add support for both methods for both devices going forward, let talk about this .
> > Sorry closed the PR by mistake
> 
> The input data shouldn't matter here. I think that there is space to match both, the same model could be used for batteries, hydrogen, hydro. Anything with a book keeping of energy + a storage target should can be modeled this way.
I agree, I was just pointing the difference.

2021-02-08 12:42 UTC, claytonpbarrows reviewed
I believe that [this function](https://github.com/NREL-SIIP/PowerSimulations.jl/pull/600/files#diff-b6353133a2ca8995aa9e66adf95b718ee1decffc1b05ca83340d4dfd8b229770L777-L789) can go away.
As it stands, it removes all `HydroDispatch` variable costs and then throws warnings about not having variable costs. I think it's leftover from when we didn't have a op_cost field in HydroDispatch

2021-02-10 17:50 UTC, jd-lara commented on src/core/variables.jl
> +struct EnergySlackUp <: VariableType end
The way this is implemented, the energy targets are not slacks they are more like a surplus or a deficit. We should use better terminology to not imply these are equivalent to the slacks added via kwargs

2021-02-10 17:54 UTC, jd-lara commented on src/devices_models/devices/common/cost_functions.jl
> +    has_target_cost::Bool
Why do we need a bool here is there is also the field additional linear terms? we should just add the terms if they exist.

2021-02-10 17:59 UTC, jd-lara commented on src/devices_models/devices/common/cost_functions.jl
> +function add_to_cost!(
I don't get what you are trying to do here. You pass the spec and the cost_data simultaneously which in a way have the same information.

2021-02-10 18:01 UTC, jd-lara commented on src/devices_models/devices/common/energy_balance_constraint.jl
>  function energy_balance_hydro!(
Why is this still a separate function?

2021-02-10 18:01 UTC, jd-lara commented on src/devices_models/devices/common_models.jl
> +get_target_multiplier(v::PSY.HydroEnergyReservoir) = PSY.get_storage_capacity(v)
Why are these here, they should be in the respective Storage and Hydro files.

2021-02-10 18:02 UTC, jd-lara commented on src/devices_models/devices/storage.jl
> +    ::Type{<:BookKeeping},
We need to rename BookKeeping since in principle both do bookkeeping one just happens to have reservation variables.

2021-02-10 18:03 UTC, jd-lara requested changes
We still need to work through some issues in this PR to get it right.

2021-02-17 16:07 UTC, closed without merging