Sd/initialization
NREL-SIIP/PowerSimulations.jl pull request #781
Opened 2021-11-12 17:05 UTC by sourabhdalvi

2021-11-12 17:44 UTC, jd-lara requested changes

2021-11-12 17:44 UTC, jd-lara commented on src/core/settings.jl
> +    store_initial_conditions::Bool
```suggestion
    serialize_initial_conditions::Bool
```

2021-11-12 17:44 UTC, jd-lara commented on src/core/settings.jl
> +        error(
```suggestion
       throw(IS.ConflictingInputsError(
```

2021-11-12 17:44 UTC, jd-lara commented on src/devices_models/device_constructors/thermalgeneration_constructor.jl
> +    devices = PSY.get_components(T, sys)
we should be using `get_available_components` here

2021-11-12 17:44 UTC, jd-lara commented on src/devices_models/device_constructors/thermalgeneration_constructor.jl
> +function construct_device!(
Why is this line not being covered in the tests?

2021-11-12 17:44 UTC, jd-lara commented on src/operation/decision_model.jl
> +    initialization_file::Union{AbstractString, Nothing}
```suggestion
    initialization_file::String
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/decision_model.jl
> +        initialization_file = nothing,
```suggestion
        initialization_file = "",
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/decision_model.jl
> +    initialization_file = nothing,
```suggestion
    initialization_file = "",
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/decision_model.jl
> +        if run_initialization_step
```suggestion
        if run_initialization_step && isempty(initialization_file)
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/decision_model.jl
> +            initialize!(model)
@daniel-thom here we would do something like this: 

```suggestion
            initialize!(model)
            elseif !(isempty(initialization_file)
                 # De-serialize initialization file
             else
                 error()
             end
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/emulation_model.jl
> +    initialization_file::Union{AbstractString, Nothing}
```suggestion
    initialization_file::String
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/emulation_model.jl
> +        initialization_file = nothing,
```suggestion
        initialization_file = "",
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/emulation_model.jl
> +    initialization_file = nothing,
```suggestion
    initialization_file = "",
```

2021-11-12 17:44 UTC, jd-lara commented on src/operation/emulation_model.jl
> +        if run_initialization_step
The same suggestions from above go here

2021-11-12 17:45 UTC, daniel-thom commented on src/operation/operation_model_interface.jl
> +        @error exception = (e, catch_backtrace())
Can you add some text to this log message? such as `"initialize failed"`

2021-11-12 17:48 UTC, daniel-thom approved these changes

2021-11-12 17:48 UTC, daniel-thom commented on src/core/settings.jl
> +        error(
You might want to use the IS.ConflictingInputsError exception here.

2021-11-13 22:48 UTC, jd-lara approved these changes

2021-11-13 22:48 UTC, merged